# Generated by Django 5.1 on 2024-10-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='rounds',
            field=models.IntegerField(default=1),
        ),
    ]
