# Generated by Django 5.1 on 2024-10-23 02:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workout_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
