# Generated by Django 5.1 on 2024-10-29 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_workoutgroup_routine_of_the_day_and_more'),
        ('workouts', '0003_alter_routine_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='groups.workoutgroup'),
        ),
        migrations.AddField(
            model_name='workout',
            name='shared_with_group',
            field=models.BooleanField(default=False),
        ),
    ]
