# Generated by Django 5.1 on 2024-11-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_alter_exercise_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('for_time', 'For Time'), ('amrap', 'AMRAP'), ('emom', 'EMOM'), ('rft', 'Rounds for Time'), ('chipper', 'Chipper'), ('endurance', 'Endurance'), ('tabata', 'Tabata')], max_length=20)),
            ],
        ),
    ]
