# Generated by Django 5.1 on 2024-11-18 01:45

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_routine_type_workout_time_alter_workout_reps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownworkout',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='knownworkout',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
