# Generated by Django 5.1 on 2024-11-26 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_knownworkout_date_knownworkout_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='abbreviation',
            field=models.CharField(blank=True, default='--', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='workouts.exercise'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='target_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='target_reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='target_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='injuryhistory',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='injuryhistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knownworkout',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='knownworkout',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knownworkout',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='knownworkout',
            name='type',
            field=models.CharField(blank=True, choices=[('for_time', 'For Time'), ('amrap', 'AMRAP'), ('emom', 'EMOM'), ('rft', 'Rounds for Time'), ('chipper', 'Chipper'), ('endurance', 'Endurance'), ('tabata', 'Tabata')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='restperiod',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='shared_with_group',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
