# Generated by Django 5.1 on 2025-01-08 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_goals_is_completed_goals_notes_goals_target_rounds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='achieved_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
