# Generated by Django 5.1 on 2024-10-29 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('workouts', '0003_alter_routine_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutgroup',
            name='routine_of_the_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_group_routine', to='workouts.routine'),
        ),
        migrations.DeleteModel(
            name='ProgressTracking',
        ),
    ]
